### ISSUE TITLE
Remove Multiple Keyboard Shortcuts for Single Operators?

### ISSUE THREAD

**Issue by doakey3** [GDquest/Blender-power-sequencer#105]
Currently, the way some operators work, multiple keyboard shortcuts are mapped to a single operator. This causes a couple issues.

When users go to User `Preferences > Input >  Sequencer` to change the keyboard shortcut, they will see multiple keyboard shortcuts for the same operator. For example, one of the shortcuts for "Copy Selected Sequences" is listed as "CTRL X", which of course is actually for cutting, not copying.

This isn't really a big deal, except that it also kind of ruins my method for using a JSON file for setting keyboard shortcuts. (A JSON, like a dictionary, can only store 1 value per key. Sure I could make the value into a list of items and store multiple functions for a single keyboard shortcut, but I think that looks ugly when the whole point was to make the JSON something people could easily edit.)

At any rate, either we need to make separate operators for each keyboard shortcut (my vote), or I need to rethink my method for importing/exporting/setting the keymap. I think the docs would be made simpler if there were a single shortcut for each op as well.

From what I can tell, the operators that have multiple shortcuts are:
* ~~change_playback_speed~~
* ~~copy_selected_sequences~~
* fade_strips
* mouse_cut
* mouse_trim
* channel_offset
* smart_snap
* toggle_selected_mute

**Comment by NathanLovato** [comment]
I don't know if this is a good idea. Your suggestion means we can't use operator properties. We'd have to create a new operator for each variation instead of changing a setting. It also means we have to split the code for the operators above into more files instead of encapsulating them. Having 2 or more shortcuts for the same operator is also common in Blender.

I don't expect the users to go the JSON by hand. Especially as you implemented an export feature. Even more so if the add-on ships with 2 or 3 profiles eventually (#106 )

That said when the op name could make more sense I totally agree we should split it. It's the case for cutting to the clipboard, and we can do this for channel_offset too at least.

For the modal mouse_cut the issue is being able to cut and trim efficiently from multiple keys. I've experimented a lot with trim and cut for instance. At first they were logically separated in the code but it caused issues on the UX side: right now you Ctrl [Shift] click to cut, trim, cut all channels or trim all channels. It's the one operation you do 100s of times a day as an editor. You can experiment splitting it up but to get the same controls I'd bet it'll take as much time as changing the JSON export.

So yeah I'm really not sold on not supporting operator properties and making shortcuts less flexible than Blender's default system. All that is why I had postponed the shortcuts tools to 1.1 or 1.2 and put it up for discussion: it's not the easiest task.

If you're busy and you'd like me to look into it no problem. It's not too complicated of a change.

**Comment by NathanLovato** [comment]
By the way I saw you changed `change_playback_speed` -> with the new design it's 6 key presses to change from normal to double speed back and forth, something I do all the time on the job. That's why the operator was designed the way it was. That's typically an example where I would rather not have us use 5 operators just to tweak one setting.

**Comment by NathanLovato** [comment]
Another thing about forcing to register shortcuts: although it's a common practice with blender add-ons, it's one I find strange. Every time you save your user settings, if you have a profile, it'll save them in and re-add the shortcuts on top of it next time you add Blender. Say you change a setting, deactivate an add-on... it'll still do it.

It can mess up your profile pretty bad. That's why until now the add-on shipped with a profile to install manually instead of having a function that burns the keymaps in the current profile. There are a few ways to manage this, not sure which is best to be honest.

**Comment by doakey3** [comment]
> when you change an existing feature's design, let's first at least discuss it real quick

When I [read this issue](https://github.com/GDquest/Blender-power-sequencer/issues/23), I thought we were going in that direction. I will be more careful.

> It can mess up your profile pretty bad.

It sounds like we need a dialog that pops up when users install the addon. The dialog can show what shortcuts the addon intends to make, what conflicts are present, and maybe even let the user edit the shortcuts before they are registered.

I'll have to play around with this this weekend and see if there can be a good way to initialize a keymap, but respect changes made to the user profile.

**Comment by NathanLovato** [comment]
> When I read this issue, I thought we were going in that direction. I will be more careful.

Ah yeah it was about adding this while keeping the other operator too. No worries it's a small thing anyway

Thank you very much again for your time :)

**Comment by doakey3** [comment]
> Every time you save your user settings, if you have a profile, it'll save them in and re-add the shortcuts on top of it next time you add Blender. Say you change a setting, deactivate an add-on... it'll still do it.

Sorry, can you describe this dilemma a bit further? I did a test today. I installed Power Sequencer, saved user settings, then went into the __init__.py and turned off registering the keyboard shortcuts and restarted Blender. None of the keyboard shortcuts were working. It seems to me that this is the proper behavior.

**Comment by NathanLovato** [comment]
Ah forget it I see why - yeah no problem, it's my bad. I had an old version of the shortcuts profile
