### ISSUE TITLE
Add a shortcut profile for NLE users

### ISSUE THREAD

**Issue by tin2tin** [GDquest/Blender-power-sequencer#106]
I noticed that playback speed was added to shortcut keys, which is really great, but I had me thinking that maybe now is the time to turn the VSE shortcuts into the NLE standard keys? 

You probably know this, but most NLEs are using:
'J' for play(shuttle) backward. Additional keypresses on 'J' will give more speed backward.
'L' for play(shuttle) forward. Additional keypresses on 'L' will give more speed forward.
'K'  for stop.
'C' for cut (Razor)
'Space' for play & stop. 

I know that these shortcuts are used for other purposes in Blender, but these keys are like w, a, s, d keys for first-person shooters. They are standard. And it is utterly confusing to switch back and forth between a NLE and the VSE. That 'space' isn't 'stop' - is enough to drive me crazy.  :-)

Ex.:
Final Cut: https://filmora.wondershare.com/final-cut-pro/final-cut-pro-shortcuts.html
Premiere Pro: https://helpx.adobe.com/premiere-pro/using/default-keyboard-shortcuts-cc.html
Avid: http://resources.avid.com/SupportFiles/attach/70024_MediaComposer_FilmComposer_Keyboard.pdf

**Comment by NathanLovato** [comment]
It's possible but won't be the default, because:
- Blender's sequencer is not an NLE and the developers are against making it work like an NLE. No tracks, bins, etc. It's designed for animation studios I think
- The shortcuts are designed for Blender users. G to grab, K for the Knife, Space for the command palette... the VSE users are Blender users first and foremost

That said, thanks to Daniel's work it's possible for an experienced video editor to create and share a profile for this that's easy to load for the add-on. Just give us time to finalize the feature and then it'll be as simple as changing the letters/keys in a text (json) file and sending it back to us to include in the add-on :)

**Comment by tin2tin** [comment]
Then maybe as a layer ex. Alt+J, Alt+K, Alt+L, Alt+C, Alt+Space?

On bins, did you see Tonton is working on Bins? [https://blenderartists.org/forum/showthread.php?444381-Blender-Edit-VSE-Bin-ability-multi-user-project-and-extra-sequencer-UI-operators](https://blenderartists.org/forum/showthread.php?444381-Blender-Edit-VSE-Bin-ability-multi-user-project-and-extra-sequencer-UI-operators)

**Comment by NathanLovato** [comment]
Using Alt or modifiers for everything, I don't think that's a good idea. Again: blender isn't an NLE, it doesn't work like an NLE. So as far as this add-on is concerned it's not going to go the NLE route by default. Having alt or modifiers on all shortcuts would be very inefficient. Plus with its growing features list, it's soon gonna be impossible: some builtin tools already use Ctrl, Alt and Shift for feature variations.

But I don't mind having a separate, well-designed shortcut profile you can install and set as default in a few clicks.

**Comment by doakey3** [comment]
> Just give us time to finalize the feature and then it'll be as simple as changing the letters/keys in a text (json) file and sending it back to us to include in the add-on :)

I agree. When this feature is done, we could ship the addon with several pre-made keymap profiles that suit different user styles.

**Comment by NathanLovato** [comment]
Note we'll need someone who's got a lot of experience with NLEs ideally to give us a hand with this. I did use Vegas to edit at first but it didn't seem too standard, and then Resolve but not for a long time as for Youtube tutorials the workflow wasn't super efficient - the bulk of the work being cutting video, audio and inserting images.

**Comment by tin2tin** [comment]
Premiere and Final Cut keymaps for Blender here: [http://www.paulcaggegi.com/video-editing-using-the-blender-vse/](http://www.paulcaggegi.com/video-editing-using-the-blender-vse/)

**Comment by doakey3** [comment]
Thanks for the links @tin2tin . I made some profiles the addon can load from it's preferences window. There's a problem though. A lot of the keyboard shortcuts that @NathanLovato made are in conflict with the shortcuts in [Paul O Caggegi's keymaps](http://www.paulcaggegi.com/video-editing-using-the-blender-vse/). Thus, these profiles are just copies of those scripts, for now.

So the question is how do I add Power-Sequencer hotkeys? Which Premiere shortcuts should I change? Which Power-Sequencer hotkeys should I change?

Consider this task:
1. Use [Paul O Caggegi's keymaps](http://www.paulcaggegi.com/video-editing-using-the-blender-vse/) to add the premiere/FCP shortcuts to blender
2. Install Power-Sequencer with the default profile
3. Use the menu in `User Preferences > Input` and change the Power-Sequencer shortcuts to something that suits you.
4. Use the `Export Keymap ` Function in Power-Sequencer's preferences menu to export only the Power-Sequencer shortcuts to a JSON file.
5. Upload that JSON file to github

I could then add these shortcuts to the profile for Final Cut Pro and Premiere. I can't do this task because I'm not familiar enough with Premiere/Final Cut to know which keyboard shortcuts I should change and which I should not.

**Comment by NathanLovato** [comment]
As nobody used them or contributed to them, we removed the shortcut profiles and now the add-on uses regular blender shortcuts. I'm not against having alternate keymaps and a system to support them if someone can work on it, maintain it, and if there are users for it in the future. For the moment though it's not going to happen. Thanks for the suggestion but I'm closing this issue for now.
