### ISSUE TITLE
Add-on updater support

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#12]
Add support for CGCookie's [Blender auto-updater](https://github.com/CGCookie/blender-addon-updater)

**Comment by NathanLovato** [comment]
With CGCookie's tutorial, it's possible for any python developer to add support for this.  If you want to help, that'd be much appreciated! It'll make the add-on a lot more convenient to use for everyone.

**Comment by TheDuckCow** [comment]
Hello there, glad to see the interest in the updater - and apologies in advance for the long comment, just wanting to cover everything. I've forked this repo and implemented a version of the updater code (mild enhancements to what's currently released). I will be happy to submit a pull request, but allow me to ask a few configuration questions for you first:

1. Right now it is setup with the ability to directly update to master (if you go into user preferences). This can be turned off so it will only allow updating/reverting to named releases - let me know
2. Right now you have two tags/releases, "1.0 beta" and "1.0 alpha"; I will need to know what the first name will be for the *first* release containing the updater code, so the minimum will be set to that release number
3. Currently I have modified the `skip_tag_function` so that it will **not** show alpha releases, but will show beta releases (and trigger update notices for them). Depending on how you want to name your releases, may need to revisit/modify this, and also modify based on when you want people to be notified of releases (ie not for alpha, but yes for betas, or only for full releases, etc)
3. I have set it up so that auto-check for update is enabled by default, with a timespan of 1 day (ie check once per day). This will notify users if an update is ready at most once per blender session once per day when they first hover their view over sequence editor window. 
    - Another option would be disable auto-check by default
    - Another option would be to not allow auto-check at all, and only have users go to preferences to check for updates
    - Note that I created and appended the draw function `draw_check_for_update` in the `handlers.py` file, next to where the playback speed dropdown code is. There likely is a better place to trigger this background check for update, but I don't see a UI panel is defined anywhere (which is where this normally goes). No real issue with it being defined here.
4. Somewhat critical note, right now your blender code says "0.9.0" and the release page says "1.0", these need to match. I recommend renaming the releases to say 0.9.0 instead of 1.0, and moving forward use release names (ie in the title of the release) which exactly match the bl_info found in the __init__ file
    - FYI, a release name with "1.0" is interpreted as "0.1.0" and would thus think that is older than "0.9.0". Safest to use 3 digits for comparison purposes.
5. I see you have multiple attachments in the release page; please note that as implemented right now, it will pull updates from the default release link/zip, e.g. https://github.com/GDquest/Blender-power-sequencer/archive/1.0-beta.zip (which works fine per my current testing). 


And by the way, this is what the popup looks like now when you do your testing. Popup is only triggered once per blender session when an update is ready, and if user selects "ignore" and presses OK, the popup won't show again (otherwise, it will continue to pop up each time they tab over to the sequencer once per blender session):
![power-sequencer-update-popup](https://user-images.githubusercontent.com/2958461/34464917-1dee8f14-ee64-11e7-803d-feffe3838845.png)

And user preferences looks like this:
![user_prefs](https://user-images.githubusercontent.com/2958461/34464921-2d876a7c-ee64-11e7-8a3d-5394f0c850f8.png)

**Comment by NathanLovato** [comment]
Hey, thanks much for the help! This is so cool to see someone work on this, otherwise it'd have stayed in the backlog for a long time.

1. If I get this right, the auto update will go to named versions but the user can choose to install the latest master as well? If so that's cool, so people can try out new tools as they come out. As new features are often self-contained in new operators the master branch is generally stable enough even for production work. I always work with it anyway, and edit videos very often ^^
2. If it's ready, let's merge it and make it part of 1.0 :) / I changed the tags already for 0.9.0 (1.0 beta) and 0.9.0-alpha (alpha, an unfinished and slightly broken release people shouldn't use on the day job)
3. Yeah better not show alpha and show beta.
4. Auto-check is fine, once a day seems reasonable as well.
  - I hope some more experienced Python dev can look at the project structure in the future and help us reorganize it. With some more work we could suggest the add-on to become part of Blender. then I think the structure is 1 operator per file, with strict naming conventions, and using folders to group them instead?
5. Thanks, fixed and we'll always use x.x.x from now on
6. Okay, to start with it should be easy enough to bundle the keymaps with the add-on and add a button in the preferences to import it as a new keymap. This way we only need 1 zip.
  - So it does use the custom zip release and not the generated source code archive, right? That'd be perfect, although after the merge we should probably move the add-on into a folder and keep the img/ and README (+ LICENSE) separate at the root.

Thank you very much for the help, greatly appreciated :)

**Comment by TheDuckCow** [comment]
Glad to pull the feature forward, I think it'll be beneficial! Responding back:

1. Yes that is how it works. You can test it as-is off of the [fork here](https://github.com/TheDuckCow/Blender-power-sequencer)
2. Yup, I see it comes through correctly now in the addon's updater interface. I'll push an update so that it will treat 1.0.0 as the minimum version for the updater.
3. Already good 👍
4. Structure can vary a lot, depends on the size of the operator and so forth. Perhaps down the line you can speak more directly with someone at the foundation if you have specific structure questions, as addons out there can vary a lot as you might imagine.
5. 👍
6. No, right now it DOES use the auto generated source code. If it's really needed to be able to pull custom build name, I could potentially work with you to get it to utilize the attached zip files to a release instead of the source code itself, but would need a little additional coding. Main thing I'd say for now, see if works for you right now as you'd expect, if it does as is (which to me it seems like it does) than maybe no changes are needed.

If you're fine with [the fork](https://github.com/TheDuckCow/Blender-power-sequencer) as it is now and thinking no changes needed, I'll make the one change asserting the min version to be 1.0.0 and then it'll be good to go.

**Comment by NathanLovato** [comment]
> No, right now it DOES use the auto generated source code.

Okay then let's use this, I guess this is all good if it works :). Thanks, merging now!
