### ISSUE TITLE
Multithreaded render: add progress report

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#151]
It should be possible to get the currently rendered frame from the Blender processes and to print some render progress from that, in frames.

**Comment by sudopluto** [comment]
might pick this up eventually. the progress of the pool of workers is trivial, and we have an example for printing progress from ffmpeg for the concat and audio joining. 
--------------------
the real problem is blender, it is very verbose and thus overloads the pipe for Popen and leads into hangs. there is a workaround by using communicate(), but I have yet to read up on that

there is also the design portion of printing progress from blender workers. do  we have a table, for the 
workers and the progress? do we just print it to the console and try to distinguish using little symbols?

**Comment by NathanLovato** [comment]
Blender only has a progress bar. The only output we get from the console is the rendered frames, right? So we can't do much aside from counting them and converting that to a percentage.
And I'd just have a similar output in the console: `Render: 56.6%`... even if it's not super accurate and one of the workers can lag behind at the end, best keep it simple.
