### ISSUE TITLE
Resize meta strip to the length/duration of the strips it contains

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#202]
That's a feature I often miss lately. There should be some code in place to get a frame range from a list of strips: see preview_to_selection. If it's not a helper function already, it's a good candidate for that.

**Comment by 3pointedit** [comment]
Also would be good to trim contents of metastrip to length of metastrip when breaking them out again. Or even place a cut (at the position of the metastrip end) on the strip inside that covers the end of the metastrip.  So that you can put an audio fade on synced audio strips that are grouped inside a metastrip.

**Comment by NathanLovato** [comment]
@3pointedit Thanks! I opened another issue for that: #215
