### ISSUE TITLE
swap_strips: Swap any type of strips with same start and duration, but different channels

### ISSUE THREAD

**Issue by Blezyn** [GDquest/Blender-power-sequencer#211]
Currently the swap strips operator does not allow effect strips to be swapped. But, even though this operator possibly doesn't have many uses, I found that I was mostly using it to swap strips that start at the same frame, have same duration, are at different channels, and more specific, the one is a base video strip, while the other its effect. Consider this case:

Pre swap:
![preswap](https://user-images.githubusercontent.com/42165833/44744473-e03fc400-ab0d-11e8-9748-d172384de3be.png)

After swap:
![afterswap](https://user-images.githubusercontent.com/42165833/44744523-006f8300-ab0e-11e8-80ce-c5a5d5fdee38.png)

or even between 2 effect strips

Pre swap:
![preswap2](https://user-images.githubusercontent.com/42165833/44744574-2137d880-ab0e-11e8-8c04-47cf441181dc.png)

After swap:
![afterswap2](https://user-images.githubusercontent.com/42165833/44744576-25fc8c80-ab0e-11e8-89e4-fb818a77fcbf.png)

I think this corresponds better to what the user expects from an operator called swap strips.
I worked on a prototype and this enhancement translates to minimal code additions.

**Comment by NathanLovato** [comment]
In this case, I think like Blender's built-in swap strips (Alt right / Alt left), it'd be nice for the tool to automatically find the strip to swap with the selected strip. You can add this without breaking the current functionality:

- in invoke, if there's only 1 strip selected, try to find the closest strip in the given direction (up or down, left or right) and store both strips. If there's two strips selected you don't do anything
- Then apply the swap in execute. If there's 2 strips selected, swap them instead

This extends the existing functionality, automating selections a little bit, in Power Sequencer's spirit.

## But!

As you said, there are few uses for a pure swap tool. My only issue with Blender's default one is it only works with the active strip, and ignores linked times. 

The add-on also comes with an operator named `power_sequencer.channel_offset`. I would reuse your logic in there so that:

1. If the selected sequences span over a single channel and
2. if you can find a matching block of linked sequence in the channel you want to move to
3. Then swap both selections

That would be a nice UX improvement! If you're up for trying this one out, I think there's some logic in the codebase to do some of that. Do you use Discord? We could do some pair programming sometime, or rather work on the add-on side-by-side, so I stay at your disposal to answer your questions, point out util functions we could use, etc.

Or we can use the official blender-python server on IRC if you prefer that.

**Comment by Blezyn** [comment]
Sounds great. I have Discord, but how can we connect, without publishing here our user ids?

**Comment by NathanLovato** [comment]
Just add me: gdquest#4637
People add me all the time anyway, I doubt posting my id here will make a big difference 😄
