### ISSUE TITLE
How can we improve the docs and your learning experience?

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#267]
Power sequencer currently comes with [a feature table](http://gdquest.com/blender/power-sequencer/docs/) thanks to @doakey3. We also have [video tutorials](https://www.youtube.com/watch?v=Zcj4onvP06w&list=PLhqJJNjsQ7KFjp88Cu57Zb9_wFt7nlkEI) to help you get started with the sequencer in general and the add-on in particular.

We also have the change log to help you track new features, bug fixes, and improvements: https://github.com/GDquest/Blender-power-sequencer/blob/master/changelog.md

How can we improve **your** learning experience? What's missing?
I would also like to make it easier for people to contribute to the docs. We have tools in place to create mini tutorials on the website (which is also open source), but no one contributed content since the 1.0 release. Any suggestions on that?

**Comment by aditiapratama** [comment]
As for **feature table**, I think there are room for improvement, such as make left side is static/floating, while the content is scrollable. I can work on this task by the way.

Some example,
- https://docs.blender.org/manual/en/dev/
- https://machin3.io/MESHmachine/docs/#features

For **video tutorials**, IMO currently it addresses a power user rather than entry level. Maybe we can create a beginner level tutorial for video editing which using BPS Workflow.

**Comment by NathanLovato** [comment]
I'm mostly interested in *your* learning experience: getting feedback on what worked for you, what's missing, what you'd like to see. More so than guesses on what may benefit others or attract new users. And the more specific the better: which tutorials are missing? Which topics would you like to see covered?

**Comment by NathanLovato** [comment]
Agreed for the side menu - currently gdquest.com doesn't have a complete template for docs. If you want to help there, that'd be much welcome!

**Comment by aditiapratama** [comment]
> Agreed for the side menu - currently gdquest.com doesn't have a complete template for docs. If you want to help there, that'd be much welcome!

I already fork the website and now still trying to build the site locally, haven't tried Hugo before :)

**Comment by NathanLovato** [comment]
Thanks! @aditiapratama if you need help to get started, we can open an issue on the gdquest.com repo and discuss it there: https://github.com/GDquest/GDquest-website/issues

**Comment by NathanLovato** [comment]
> Maybe quick 1 minute videos about each operator in specific? These would be awesome

That's +/- the plan with new features and updates, but maybe not 1 minute: these wouldn't work well for youtube, I'm afraid few people would ever watch them, limiting their organic reach a lot and making them a bad time investment (humans being lazy, having to go through 50 video pages and counting would be a pain)
 
How about 3-5 minute tuts that group related functioinality together ; not only show how one operator works, but how it fits into the editing workflow? Always showing concrete use cases.

E.g. showing all the mouse cut tools and how to use them most effectively:

- to keep video and audio in sync
- to edit audio separately from video
- how it compares to using the keyboard-based workflow

Any requests for specific tutorials? This would help a lot.

**Comment by henriiquecampos** [comment]
Hey there, so let's see...

## Documentation

Well for me, I mostly prefer use built-in docs, I dunno if is possible to attach the README docs to the plugin and somehow when the user click on Documentation, in User Preferences -> Addon -> VSE: Power Sequencer, it would open it. Whenever I wanted to see which were the power sequencer features I could use, I went to the User Preferences -> Input -> `power_sequencer`. But to be honest this didn't help a lot, because well...I knew they were available but neither I knew how to use them, besides the shortcut, nor how they work.

### Small insight
I actually used the README around 3 times, especially at the beginning, it is very well done and is a good source of information, but as @guilhermehto said, most users won't get here on GitHub. The idea of using an YouTube playlist when we click on `Documentation` in the add-on is a good shot, but I think that layering it through GitHub could be more insightful for users. By layering I mean: when clicking in Documentation it would open the README page, which had a link to the videos playlist.

In resume: the documentation as is, is good already, is easy to get to where you want, since we can share links that send directly to the feature/instruction. I wouldn't change it to be honest.

## Learning Experience

I don't think I actually know how to use the addon to its full potential, but here goes stuff that helped me improve a lot the workflow, and I think there are no tuts for this yet:

- Using stylus/wacom tablet (I had one retired that now I use on a daily basis for editing, is indeed way more productive) and the addon adapt them to its context
- The core concept of the keybinding (to decrease the left-hand movement on keyboard, i.e. to keep the left-hand landed most of the time)
- Using multiple scenes for a project and batch rendering them
- Interesting settings (like is it possible to change the folders' name the Import Local Footage use?)
- Mouse Cut tricks (for instance I always got confused about if it works only in the strip the mouse is over when I release, or if it takes all the channels, use cases for remove/keep gap)
- Synergy with other Blender's operators, like I currently use snap to cursor a lot. This with the concatenation is awesome for syncing audio-video

Well I think these are my insights, I'll probably have more as I remember doubts I had/have 😁

**Comment by guilhermehto** [comment]
> How about 3-5 minute tuts that group related functioinality together ; not only show how one operator works, but how it fits into the editing workflow? Always showing concrete use cases.

Yep! That would be perfect!

**Comment by NathanLovato** [comment]
Got some pointers as to what to do in the near future so closing for now
