### ISSUE TITLE
copy_selected_sequences failing due to wrong access

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Blender-power-sequencer#278]
Currently the [`copy_selected_sequences`](https://github.com/GDquest/Blender-power-sequencer/blob/master/operators/copy_selected_sequences.py) fail to execute because `context.selection` is not valid. And due to it overriding the default copy-paste behavior, it is always failing to copy strips.

**Comment by razcore-art** [comment]
It's all good, the operator works. Could you change to `context` (the passed in parameter to `execution`) instead of `bpy.context`, because that's how these operators are supposed to work since they can receive a different context other than `bpy.context`. Than it will be all good. I mean fix this as well since you're at it :)

**Comment by razcore-art** [comment]
Aactually I'll do the `context` fix cause there's a lot of place where this needs to be done
