### ISSUE TITLE
Error registering shortcuts on init

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#292]
![image](https://user-images.githubusercontent.com/12694995/49259897-80dfb000-f47e-11e8-9391-331ca7760eab.png)

**Comment by razcore-art** [comment]
This is most likely a new operator that doesn't have a correct `doc['shortcuts']` value. We can find it if we print `bl_idname` of the operators when registering in `utils/register_shortcuts.py` as a debug step, but in this case it isn't necessary cause there's few new operators. The culprit is `operators/jump_to_cut.py` which uses an incorrect `doc['shortcuts'][_]['type']` value.

**Comment by razcore-art** [comment]
I guess you most likely want this:

```python
    doc = {
        'name': doc_name(__qualname__),
        'demo': '',
        'description': doc_description(__doc__),
        'shortcuts': [
            ({'type': 'UP_ARROW', 'value': 'PRESS'},
             {'direction': 'forward'},
             'Jump to next cut or keyframe'),
            ({'type': 'DOWN_ARROW', 'value': 'PRESS'},
             {'direction': 'backward'},
             'Jump to previous cut or keyframe'),
        ],
        'keymap': 'Frames'
    }
```
