### ISSUE TITLE
Align audio doesn't show up? 

### ISSUE THREAD

**Issue by tin2tin** [GDQuest/blender-power-sequencer#441]
Just wanted to test the audio align feature, but even though I got ffmpeg and scipy installed and two audio strips selected, the operator doesn't show up in F3 pop-up or in the Audio menu? 

Btw. the Ctrl+L displayed here seems to be a native short-cut for Select Linked.

**Comment by NathanLovato** [comment]
If you're using the version bundled in Blender, that's normal, it can't be included in built-in addons due to the dependency on the external library scipy. You have to use the version from github.

We should add a mention in the online documentation.

**Comment by tin2tin** [comment]
Now I've tried the release version here from github. Unfortunately, using audio align makes Blender hang on windows.

**Comment by NathanLovato** [comment]
That's strange, it shouldn't. At this point, I'm considering removing the tool from the add-on: it's not in the built-in version of the addon, you need an extra download...  it's a feature that's not *so* useful to me; I found that aligning two tracks with a clap by hand is pretty quick in Blender.

What do you think?

**Comment by tin2tin** [comment]
It is still a useful feature, but I don't know how much it would take to get working? Is working on other OS than Windows?

**Comment by NathanLovato** [comment]
Gotta test it again here. Maybe a recent scipy update broke it, maybe it's specific to Windows, maybe to your setup. Would you have two short audio clips I could use for testing?

A useful feature in my book is one people actually use, not one that *can* be useful.

I'm afraid people now use the version of BPS that ships with Blender and never touch this feature, except for someone who explores a bit like you. This means I have to maintain two versions of the add-on. And I don't have much time. People also almost never contribute; I mostly get support requests. That's why I'd consider dropping it and having just one version of power sequencer.

**Comment by tin2tin** [comment]
You can grab a h.264 and a mp3 here: https://archive.org/details/thecosmonaut-s045

**Comment by NathanLovato** [comment]
Thanks for the link, I'll try to get to it in the coming days; got a lot on my plate atm.

> maybe it would have a more visible life if it is an add-on of its own?

Maybe yes. If someone wanted to take the time and turn it into an add-on + promote it, that'd be most welcome. The code's open-source so anyone can do that anytime if they so desire.

**Comment by NathanLovato** [comment]
I've removed the feature from the add-on. The code's in the git history and releases up to 2.0.0 if someone wants to turn it into a new add-on.
