### ISSUE TITLE
Always use full source clip for AddSpeed

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#74]
So you can press S to slide the strip

**Comment by doakey3** [comment]
Currently the `add speed` function sets the speed of the strip to 2x and adjusts strip length accordingly. What if we made this into a modal operator where the user could adjust the speed and length of the strip immediately after adding it? This would come in handy for me since I tend to do a lot of time remapping whenever I do a tutorial.

**Comment by NathanLovato** [comment]
Yeah, actually it's not only 2x right now - it's 2x, 3x, 4x etc. 
depending on the parameter. Def. a modal operator would be nice. I'd say 
with the ability to snap to 2x, 3x etc. I don't remember exactly because 
it was a while ago but IIRC there were some issues if you tried 
remapping to e.g. 1.66 or 1.44x speed.
